name: app2
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auth_buttons: ^3.0.2
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  firebase_auth_web: ^5.11.6
  cloud_firestore: ^4.12.0
  google_sign_in_web: ^0.12.4
  meta: ^1.7.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_sign_in: ^6.2.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
