// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1GM-AFfNs81hrHkPkFAXdsR3o-fnz4ZI',
    appId: '1:367747777118:web:84742c97bd70a1b20e2acf',
    messagingSenderId: '367747777118',
    projectId: 'pet-finder-f6e8d',
    authDomain: 'pet-finder-f6e8d.firebaseapp.com',
    storageBucket: 'pet-finder-f6e8d.appspot.com',
    measurementId: 'G-31R6KLG5TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA41pfQrECWi6mKz4OicB6dp933IIX_k00',
    appId: '1:367747777118:android:45d17934a0a03d100e2acf',
    messagingSenderId: '367747777118',
    projectId: 'pet-finder-f6e8d',
    storageBucket: 'pet-finder-f6e8d.appspot.com',
  );

}